development:
  adapter: sqlite3
  database: db/database.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/database.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  encoding: utf8
  database: invoicer
  host: localhost
  username: root
  password: password